### ISSUE TITLE
return {} bug

### ISSUE THREAD

**Issue by liaohainan** [iambumblehead/form-urldecoded#1]
var uri = 'data=%5B%7B%22e%22%3A%7B%22et%22%3A%22shop%22%2C%22ref%22%3A%22%24pageName%24%3Fv%3D8%26id%3Durl%26event%3DVIEW%26time%3D1564394439489%26idlist%3Diid%22%2C%22t%22%3A1564394439489%2C%22spm%22%3A%22H5.b.c.d.95025060%22%2C%22referer%22%3A%22%22%7D%7D%5D'

return {}
when I delete code "uri.match(/\?/) && " 

result will true

**Comment by iambumblehead** [comment]
@liaohainan this string is tough to parse, decoded the string looks like this,
```
data=[{"e":{"et":"shop","ref":"$pageName$?v=8&id=url&event=VIEW&time=1564394439489&idlist=iid","t":1564394439489,"spm":"H5.b.c.d.95025060","referer":""}}]
```
