### ISSUE TITLE
Published mjs file is formatted as commonjs

### ISSUE THREAD

**Issue by frabarz** [iambumblehead/form-urldecoded#16]
Both the `js` and the `mjs` files in the package published at npm are identical. This is making compilation processes for the esm import to fail.
The solution is to replace `module.exports =` to `export default` in the `mjs` file. Just a patch version bump should be enough.

Considering the `start` script in the `package.json` file, I'm guessing at some point the `.mjs` file got replaced by the processed version.

**Comment by iambumblehead** [comment]
@frabarz thank you. I'm sorry for this regression.
