### ISSUE TITLE
decoding both '+' and '%2B' as 'whitespace'

### ISSUE THREAD

**Issue by frabarz** [iambumblehead/form-urldecoded#5]
I'm trying to decode a query string where a parameter is `measure=15%2B+Years`.  
This should be decoded as `{measure: "15+ Years"}`, but is being decoded as `{measure: "15  Years"}`.

The issue is on [line 14](https://github.com/iambumblehead/form-urldecoded/blob/baafda1238dd4a0b6bc94d5df16b4a13b4a926f6/form-urldecoded.js#L14):
```
decode = str => decodeURIComponent(str).replace(/\+/g, ' '),
```
which should be
```
decode = str => decodeURIComponent(str.replace(/\+/g, ' ')),
```
since the raw `+` should decode to `[whitespace]` before decoding the unsafe characters.

**Comment by iambumblehead** [comment]
thank you I believe this is resolved
